version: '3'
services:
  
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    volumes:
      - ./client:/app
    working_dir: /app
    ports:
      - 8001:8080

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'laravel_test'
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3306:3306'

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    volumes:
      - ./api:/var/www
    working_dir: /var/www
    ports:
      - 8000:8000
    depends_on:
      - db

  server:
    image: nginx:alpine
    volumes:
      - ./conf.d:/etc/nginx/conf.d/default.conf
    ports:
      - 81:80
    depends_on:
      - api
      - client